apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  # This is base64 encoded - replace with your actual database URL
  # To encode: echo -n "postgresql://username:password@host:5432/database" | base64
  url: cG9zdGdyZXNxbDovL2FkbWluOnBhc3N3b3JkQGNvZGUtcXVlc3QtcG9zdGdyZXMtcnV0aXJhLmNvbS5hbWF6b25hd3MuY29tOjU0MzIvY29kZXF1ZXN0
